### ISSUE TITLE
issue with stopping task with id

### ISSUE THREAD

**Issue by shabazpatel** [datmo/datmo#107]
- [x] add a task stop --all command to stop all datmo tasks
- [x] fix environment run execution to ensure that the run_id is set in the task. this will ensure stop for task will always work

**Comment by asampat3090** [comment]
working off of the [flow-issues branch](https://github.com/datmo/datmo/tree/flow-issues)

**Comment by asampat3090** [comment]
the second point was not possible, because the run may not even complete and may not be returned by docker. instead, stop tasks uses the task name which is given at create time to the environment driver. once it is stopped (and the running container removed), the task will have a status=STOPPED

commit e6347ec  has these changes

**Comment by asampat3090** [comment]
based on this we also closed #109 since it isn't necessary nor possible at the moment.

**Comment by asampat3090** [comment]
fixed with PR #115
