### ISSUE TITLE
adding try<>finally to environment dockerenv driver and controller to give back run_id to controller's task run command

### ISSUE THREAD

**Issue by shabazpatel** [datmo/datmo#109]

**Comment by asampat3090** [comment]
try, finally has already been added in tasks. try finally won't help here because run_id is based on docker environment driver and if the docker command fails there, the run_id will not be available. for now, we should not depend on this run_id, and leverage our task_ids as the key way to identify containers. 

We can only rely on run_id if the task has completed successfully. 

Closing this issue for now.
