### ISSUE TITLE
datmo task run should designate environment being used

### ISSUE THREAD

**Issue by nmwalsh** [datmo/datmo#198]
First line of `task run` should be messaging that tells the user the location of the dockerfile/env or the environment ID that is being run. 

If a user does a task run with no environments setup, it uses the docker file from the repository if available. In this case, you should also write a line that says that you created a datmo environment for the user that will automatically be used in future runs. This is important because if the user is unaware of this, and they do `task run`s after editing the Dockerfile that they brought, these changes are not automatically tracked by datmo, since datmo prioritizes the copy made in the `datmo_environments` directory.

**Comment by asampat3090** [comment]
This is related to #194. In order to do this we will need to add a `files` attribute to the environment entity. This will then allow any command that uses environments to list the exact paths to the files that make up the environment that are being used. In this way the user can locate, update, or view the environment files that make up the running environment

**Comment by asampat3090** [comment]
Closing this issue and creating a new one that is more up to date
