### ISSUE TITLE
Compare datmo to other solutions

### ISSUE THREAD

**Issue by georghildebrand** [datmo/datmo#213]
Hi all, 

very nice project. Are you thinking about adding any kind of benchmarking, comparison against other solutions such as pipelineAI or dvc?

https://github.com/PipelineAI/pipeline

https://github.com/iterative/dvc

**Comment by nmwalsh** [comment]
@georghildebrand thanks! Both PipelineAI and DVC are nice tools for their respective purposes. The primary focus of the datmo open source project is to enable streamlined environment setup, experiment reproducibility, and model versioning/tracking.

For PipelineAI, the biggest overlap would be the reproduction of environments and deployment of models. We cover environment reproduction and setup in [these examples](https://github.com/datmo/datmo/tree/master/examples#environment-setup), and have benchmarks for model deployment, a feature in our hosted product, [available here](https://blog.datmo.com/posts/pushing-the-needle-forward-for-ai-deployments/).  

As for DVC, they focus on building a reproducible procedure by creating a DAG (direct acyclic graph) for running a sequence of actions given an initial state. However, we feel like there were still some parts of experimentation that weren't covered here; for example, software environments are not replicated from machine to machine, so if environments are variable between steps or between machines, it would be hard to replicate. Further, the user experience is slightly different from datmo's open source tool. Are there any specific metrics here you'd like to see compared?

**Comment by Make42** [comment]
For recreating environments, one has poetry and for tracking poetry one has git.

There is such a ton of tracking tools available. If anything there are too many tools. This is makes finding a good MLOps (in the most general sense) tools really hard. (I am currently trying to evaluate what is available.) Creating a new project adds to that issue and additionally divides the attention instead of making a single really great tool.

A few examples of very close tools are sacred, guild.ai. Open source (but company backed) tools in the space of experiment management are all the neptune, Weights and Biases, MLRun and similar tools. Then there are all the end-to-end tools which also contain reproducibility features like ZenML, ClearML and similar tools.

All that being said: Why did you create a new tool instead of helping other tools be better?

Examples:

**Comment by georghildebrand** [comment]
thx guys, valid points. I thin its worth closing the issue.

**Comment by Make42** [comment]
https://blog.datmo.com/posts/pushing-the-needle-forward-for-ai-deployments/ is a dead link, can you update?

Also, I did not mean my question to be rhetorical... so, what is the answer?

Or is datmo not developed anymore - which would make the question obsolete, I guess. I am asking, because the last update seem to be 3 years ago.
